/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.NhanVienBLL;
import Utilities.ControlFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author RumIT
 */
public class jpanel_QLNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form jpanel_QLNhanVien
     */
    public jpanel_QLNhanVien() {
        initComponents();
        
        //load dữ liệu lên bảng danh sách nhân viên
        control.bindingNhanVien(table_DSNhanVien, nhanvienBLL.getAll());
        
        //ẩn các nút xóa, sửa, xác nhận
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
        btn_XacNhan.setEnabled(false);
        
        //đặt dữ liệu combobox
        cbb_GioiTinh.removeAllItems();
        //Cài cbb chức vụ
        cbb_ChucVu.removeAllItems();
        cbb_ChucVu.addItem("Lễ Tân");
        cbb_ChucVu.addItem("Quản lý");
        cbb_ChucVu.addItem("Quản lý2 ");
        //xóa dữ liệu trong các text field
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_NamSinh.setText("");
        cbb_ChucVu.setSelectedItem("Lễ Tân");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
        txt_GhiChu.setText("");

        table_DSNhanVien.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_DSNhanVien = new javax.swing.JTable();
        panel_Control = new javax.swing.JPanel();
        panel_ThongTin = new javax.swing.JPanel();
        lb_MaNV = new javax.swing.JLabel();
        lb_TenNV = new javax.swing.JLabel();
        lb_GioiTinh = new javax.swing.JLabel();
        lb_NamSinh = new javax.swing.JLabel();
        lb_ChucVu = new javax.swing.JLabel();
        lb_DiaChi = new javax.swing.JLabel();
        lb_SDT = new javax.swing.JLabel();
        lb_GhiChu = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        txt_NamSinh = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_GhiChu = new javax.swing.JTextField();
        cbb_GioiTinh = new javax.swing.JComboBox<>();
        cbb_ChucVu = new javax.swing.JComboBox<>();
        panel_Buttons = new javax.swing.JPanel();
        btn_Xoa = new javax.swing.JButton();
        btn_XacNhan = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        panel_TimKiem = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        lb_TimKiem = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(954, 438));
        setMinimumSize(new java.awt.Dimension(954, 438));
        setPreferredSize(new java.awt.Dimension(954, 438));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_DSNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_DSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_DSNhanVien.setRowHeight(20);
        table_DSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DSNhanVien);

        panel_Control.setBackground(new java.awt.Color(255, 255, 255));

        panel_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        panel_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔN TIN NHÂN VIÊN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_MaNV.setText("MÃ NHÂN VIÊN");

        lb_TenNV.setText("TÊN NHÂN VIÊN");

        lb_GioiTinh.setText("GIỚI TÍNH");

        lb_NamSinh.setText("NĂM SINH");

        lb_ChucVu.setText("CHỨC VỤ");

        lb_DiaChi.setText("ĐỊA CHỈ");

        lb_SDT.setText("SỐ ĐIỆN THOẠI");

        lb_GhiChu.setText("GHI CHÚ");

        txt_MaNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_TenNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_TenNV.setMaximumSize(new java.awt.Dimension(6, 20));

        txt_NamSinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_SDT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_DiaChi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_DiaChi.setMaximumSize(new java.awt.Dimension(6, 20));

        txt_GhiChu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_GhiChu.setMaximumSize(new java.awt.Dimension(6, 20));

        cbb_GioiTinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbb_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_GioiTinh.setMaximumSize(new java.awt.Dimension(6, 20));
        cbb_GioiTinh.setMinimumSize(new java.awt.Dimension(6, 20));
        cbb_GioiTinh.setPreferredSize(new java.awt.Dimension(6, 20));

        cbb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_ThongTinLayout = new javax.swing.GroupLayout(panel_ThongTin);
        panel_ThongTin.setLayout(panel_ThongTinLayout);
        panel_ThongTinLayout.setHorizontalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ThongTinLayout.createSequentialGroup()
                        .addComponent(lb_MaNV)
                        .addGap(23, 23, 23)
                        .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ThongTinLayout.createSequentialGroup()
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_TenNV)
                            .addComponent(lb_NamSinh)
                            .addComponent(lb_GioiTinh)
                            .addComponent(lb_ChucVu))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_ChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_ThongTinLayout.createSequentialGroup()
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_SDT)
                            .addComponent(lb_DiaChi)
                            .addComponent(lb_GhiChu))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panel_ThongTinLayout.setVerticalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MaNV)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TenNV)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_NamSinh)
                    .addComponent(txt_NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_GioiTinh)
                    .addComponent(cbb_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ChucVu)
                    .addComponent(cbb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_SDT)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_DiaChi)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_GhiChu)
                    .addComponent(txt_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Buttons.setBackground(new java.awt.Color(255, 255, 255));

        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/delete.png"))); // NOI18N
        btn_Xoa.setText("XÓA");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_XacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/checked.png"))); // NOI18N
        btn_XacNhan.setText("XÁC NHẬN");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/pencil.png"))); // NOI18N
        btn_Sua.setText("SỬA");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/plus.png"))); // NOI18N
        btn_Them.setText("THÊM");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ButtonsLayout = new javax.swing.GroupLayout(panel_Buttons);
        panel_Buttons.setLayout(panel_ButtonsLayout);
        panel_ButtonsLayout.setHorizontalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );
        panel_ButtonsLayout.setVerticalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ButtonsLayout.createSequentialGroup()
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Sua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_XacNhan)
                    .addComponent(btn_Them))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_ControlLayout = new javax.swing.GroupLayout(panel_Control);
        panel_Control.setLayout(panel_ControlLayout);
        panel_ControlLayout.setHorizontalGroup(
            panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Buttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_ControlLayout.setVerticalGroup(
            panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ControlLayout.createSequentialGroup()
                .addComponent(panel_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TimKiem.setBackground(new java.awt.Color(255, 255, 255));

        lb_TimKiem.setText("TÌM KIẾM");

        btn_TimKiem.setText("TÌM KIẾM");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TimKiemLayout = new javax.swing.GroupLayout(panel_TimKiem);
        panel_TimKiem.setLayout(panel_TimKiemLayout);
        panel_TimKiemLayout.setHorizontalGroup(
            panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_TimKiem)
                .addGap(18, 18, 18)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_TimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_TimKiemLayout.setVerticalGroup(
            panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TimKiem)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(panel_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panel_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(panel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //khởi tạo các đối tượng cần thiết
    ControlFormat control = new ControlFormat();
    NhanVienBLL nhanvienBLL = new NhanVienBLL();
    //
    //
    //
    
    
    
    private void table_DSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSNhanVienMouseClicked
        //lấy dòng đang chọn
        int vitri = table_DSNhanVien.getSelectedRow();
        //load dữ liệu sang các text field thông tin
        txt_MaNV.setText(table_DSNhanVien.getValueAt(vitri, 0).toString());
        txt_TenNV.setText(table_DSNhanVien.getValueAt(vitri, 1).toString());
        txt_NamSinh.setText(table_DSNhanVien.getValueAt(vitri, 2).toString());
        cbb_ChucVu.setSelectedItem(table_DSNhanVien.getValueAt(vitri, 4).toString());
        txt_SDT.setText(table_DSNhanVien.getValueAt(vitri, 5).toString());
        txt_DiaChi.setText(table_DSNhanVien.getValueAt(vitri, 6).toString());
        txt_GhiChu.setText(table_DSNhanVien.getValueAt(vitri, 7).toString());
        
        //trơ tới item ứng với bảng trong combobox
        cbb_GioiTinh.removeAllItems();
        cbb_GioiTinh.addItem("Nam");
        cbb_GioiTinh.addItem("Nữ");
        cbb_GioiTinh.addItem("Không rõ");
        cbb_GioiTinh.setSelectedItem(table_DSNhanVien.getValueAt(vitri, 3).toString());
        
        //hiển các nút Sửa Xóa
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_table_DSNhanVienMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        int vitri = table_DSNhanVien.getSelectedRow();
        int rows  = table_DSNhanVien.getRowCount();
        String macu = table_DSNhanVien.getValueAt(vitri, 0).toString();
        //lấy dữ liệu trong các text field
        String maNV = txt_MaNV.getText();
        String tenNV =  txt_TenNV.getText();
        String namSinh = txt_NamSinh.getText();
        String gioitinh = cbb_GioiTinh.getSelectedItem().toString();
        String chucVu = cbb_ChucVu.getSelectedItem().toString();
        String SDT = txt_SDT.getText();
        String diaChi = txt_DiaChi.getText();
        String ghiChu = txt_GhiChu.getText();

        
        //kiểm trả mã nhân viên và thực hiện việc sửa
        boolean kiemtra = true;
        for(int i = 0; i < rows; i++){
            if(i == vitri)          //dòng đang xét trùng với vị trí ta chọn trên bảng
                continue;
            if(maNV.equals(table_DSNhanVien.getValueAt(i, 0).toString())){
                kiemtra = false;
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại");
                txt_MaNV.setText("");
                break;
            }
        }
        if(kiemtra == true){
            //ghi dữ liệu
            if(nhanvienBLL.suaNhanVien(maNV, tenNV, namSinh, gioitinh, chucVu, SDT, diaChi, ghiChu, macu)){
                //thông báo
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                //đặt lại các trường
                txt_MaNV.setText("");
                txt_TenNV.setText("");
                txt_NamSinh.setText("");
                cbb_ChucVu.setSelectedItem("Lễ Tân");
                txt_SDT.setText("");
                txt_DiaChi.setText("");
                txt_GhiChu.setText("");
                cbb_GioiTinh.removeAllItems();
                //load lại dữ liệu
                control.bindingNhanVien(table_DSNhanVien, nhanvienBLL.getAll());
            }else
                JOptionPane.showMessageDialog(this, "Không sửa được");
            
        }
        
        
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        //Xóa các trường text để nhập
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_NamSinh.setText("");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
        txt_GhiChu.setText("");
        //đặt item trong combobox giới tính
        cbb_GioiTinh.removeAllItems();
        cbb_GioiTinh.addItem("Nam");
        cbb_GioiTinh.addItem("Nữ");
        cbb_GioiTinh.addItem("Không rõ");
        //ẩn các nút thêm, sửa và xóa đồng thời hiện nút xác nhận
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
        btn_Them.setEnabled(false);
        btn_XacNhan.setEnabled(true);
        //xóa chọn trên bảng
        table_DSNhanVien.clearSelection();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        //Lấy dữ liệu vừa nhập
        String maNV = txt_MaNV.getText();
        String tenNV =  txt_TenNV.getText();
        String namSinh = txt_NamSinh.getText();
        String gioitinh = cbb_GioiTinh.getSelectedItem().toString();
        String chucVu = cbb_ChucVu.getSelectedItem().toString();
        String SDT = txt_SDT.getText();
        String diaChi = txt_DiaChi.getText();
        String ghiChu = txt_GhiChu.getText();
        String matkhau = "12345";
        if(maNV.equals("")||tenNV.equals("")||namSinh.equals("")||chucVu.equals("")||SDT.equals("")||diaChi.equals("")||ghiChu.equals("")){
            JOptionPane.showMessageDialog(this, "Không được bỏ trống trường nào");
        }else{
        
        //kiểm tra xem có trùng mã nhân viên hay không
        int rows = table_DSNhanVien.getRowCount();
        
        boolean kiemtra = true;
        for(int i = 0; i < rows; i++){
            if(maNV.equals(table_DSNhanVien.getValueAt(i, 0).toString())){
                kiemtra = false;
                JOptionPane.showMessageDialog(this, "Mã bị trùng");
                break;
            }
        }
        if(kiemtra == true){
            //ghi dữ liệu
            if(nhanvienBLL.themNhanVien(maNV, tenNV, namSinh, gioitinh, chucVu, SDT, diaChi, ghiChu,matkhau)){
            //thông báo
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            //load lại bảng
            control.bindingNhanVien(table_DSNhanVien, nhanvienBLL.getAll());
            //xóa các text field và đăt lại các nút
            txt_MaNV.setText("");
            txt_TenNV.setText("");
            txt_NamSinh.setText("");

            txt_SDT.setText("");
            txt_DiaChi.setText("");
            txt_GhiChu.setText("");
            cbb_GioiTinh.removeAllItems();
            btn_Them.setEnabled(true);
            btn_XacNhan.setEnabled(false);
            
            }
        }
        }
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        String key = txt_TimKiem.getText();
        control.bindingNhanVien(table_DSNhanVien, nhanvienBLL.timkiem(key));
        txt_TimKiem.setText("");
        
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        
    }//GEN-LAST:event_btn_XoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_ChucVu;
    private javax.swing.JComboBox<String> cbb_GioiTinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_ChucVu;
    private javax.swing.JLabel lb_DiaChi;
    private javax.swing.JLabel lb_GhiChu;
    private javax.swing.JLabel lb_GioiTinh;
    private javax.swing.JLabel lb_MaNV;
    private javax.swing.JLabel lb_NamSinh;
    private javax.swing.JLabel lb_SDT;
    private javax.swing.JLabel lb_TenNV;
    private javax.swing.JLabel lb_TimKiem;
    private javax.swing.JPanel panel_Buttons;
    private javax.swing.JPanel panel_Control;
    private javax.swing.JPanel panel_ThongTin;
    private javax.swing.JPanel panel_TimKiem;
    private javax.swing.JTable table_DSNhanVien;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_GhiChu;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_NamSinh;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
