/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CT_PhieuDichVuBLL;
import BLL.HoaDonBLL;
import BLL.KhachHangBLL;
import BLL.PhieuDichVuBLL;
import BLL.PhieuThuePhongBLL;
import Utilities.ControlFormat;

/**
 *
 * @author RumIT
 */
public class jpanel_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form jpanel_ThongKe
     */
    public jpanel_ThongKe() {
        initComponents();
        control.bindingThongKe(table_ThongKe, hoadonBLL.thongke());
        //table_ThongKe.getTableHeader().set
        //cài đặt cbb tháng
        cbb_Thang.removeAllItems();
        cbb_Thang.addItem("Tất cả");
        cbb_Thang.addItem("1");
        cbb_Thang.addItem("2");
        cbb_Thang.addItem("3");
        cbb_Thang.addItem("4");
        cbb_Thang.addItem("5");
        cbb_Thang.addItem("6");
        cbb_Thang.addItem("7");
        cbb_Thang.addItem("8");
        cbb_Thang.addItem("9");
        cbb_Thang.addItem("10");
        cbb_Thang.addItem("11");
        cbb_Thang.addItem("12");
        cbb_Thang.setSelectedItem("Tất cả");
        
        //Cài đặt cbb năm
        cbb_Nam.removeAllItems();
        cbb_Nam.addItem("Tất cả");
        //Lấy tất cả các năm hóa đơn trong CSDL
        for(String nam : hoadonBLL.layDSNam()){
            cbb_Nam.addItem(nam);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        panel_Title = new javax.swing.JPanel();
        lb_Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ThongKe = new javax.swing.JTable();
        panel_Loc = new javax.swing.JPanel();
        cbb_Nam = new javax.swing.JComboBox<>();
        lb_NAm = new javax.swing.JLabel();
        cbb_Thang = new javax.swing.JComboBox<>();
        lb_Thang = new javax.swing.JLabel();
        btn_Xem = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1054, 491));
        setMinimumSize(new java.awt.Dimension(1054, 491));

        panel_bg.setBackground(new java.awt.Color(255, 255, 255));

        panel_Title.setBackground(new java.awt.Color(255, 255, 255));
        panel_Title.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_Title.setBackground(new java.awt.Color(23, 93, 88));
        lb_Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(23, 93, 88));
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("THỐNG KÊ");

        javax.swing.GroupLayout panel_TitleLayout = new javax.swing.GroupLayout(panel_Title);
        panel_Title.setLayout(panel_TitleLayout);
        panel_TitleLayout.setHorizontalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_TitleLayout.setVerticalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        table_ThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_ThongKe);

        panel_Loc.setBackground(new java.awt.Color(255, 255, 255));

        cbb_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_NAm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_NAm.setText("NĂM");

        cbb_Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_Thang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_Thang.setText("THÁNG");

        btn_Xem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xem.setText("XEM");
        btn_Xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_LocLayout = new javax.swing.GroupLayout(panel_Loc);
        panel_Loc.setLayout(panel_LocLayout);
        panel_LocLayout.setHorizontalGroup(
            panel_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Thang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_NAm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_LocLayout.setVerticalGroup(
            panel_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Thang)
                    .addComponent(lb_NAm)
                    .addComponent(cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xem))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(panel_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addComponent(panel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XemActionPerformed
        String thang = cbb_Thang.getSelectedItem().toString();
        String nam = cbb_Nam.getSelectedItem().toString();
        
        if(thang.equals("Tất cả")){
            if(nam.equals("Tất cả")){
                control.bindingThongKe(table_ThongKe, hoadonBLL.thongke());
            }else{
                control.bindingThongKe(table_ThongKe, hoadonBLL.thongkeTheoNam(nam));
            }
        }else{
            if(nam.equals("Tất cả")){
                control.bindingThongKe(table_ThongKe, hoadonBLL.thongkeTheoThang(thang));
            }else{
                control.bindingThongKe(table_ThongKe, hoadonBLL.thongkeTheoThangVaNam(thang,nam));
            }
        }
    }//GEN-LAST:event_btn_XemActionPerformed
    //khởi tạo đối tượng cần thiết
    ControlFormat control = new ControlFormat();
    HoaDonBLL hoadonBLL = new HoaDonBLL();
    KhachHangBLL khachBLL = new KhachHangBLL();
    PhieuThuePhongBLL phieuthueBLL = new PhieuThuePhongBLL();
    CT_PhieuDichVuBLL ctPhieuDVBLL = new CT_PhieuDichVuBLL();
    PhieuDichVuBLL phieudichvuBLL = new PhieuDichVuBLL();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Xem;
    private javax.swing.JComboBox<String> cbb_Nam;
    private javax.swing.JComboBox<String> cbb_Thang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_NAm;
    private javax.swing.JLabel lb_Thang;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JPanel panel_Loc;
    private javax.swing.JPanel panel_Title;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JTable table_ThongKe;
    // End of variables declaration//GEN-END:variables
}
