/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JPanel;

/**
 *
 * @author RumIT
 */
public class jpanel_QuanLy extends javax.swing.JPanel {

    /**
     * Creates new form jpanel_QuanLy
     */
    public jpanel_QuanLy() {
        initComponents();
        this.setVisible(true);
    }
    
    public jpanel_QuanLy(String chuc){
        initComponents();
        this.setVisible(true);
        chucvu = chuc;
        if(chucvu.equals("Lễ Tân")){
            btn_QLPhong.setEnabled(false);
            btn_QLNhanVien.setEnabled(false);
            btn_QLDichVu.setEnabled(false);
            btn_QLLoaiPhong.setEnabled(false);
            btn_QLKhachHang.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Bg = new javax.swing.JPanel();
        panel_ToolBar = new javax.swing.JPanel();
        btn_QLPhong = new javax.swing.JButton();
        btn_QLDichVu = new javax.swing.JButton();
        btn_QLKhachHang = new javax.swing.JButton();
        btn_QLNhanVien = new javax.swing.JButton();
        btn_QLLoaiPhong = new javax.swing.JButton();
        panel_Content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1054, 491));
        setMinimumSize(new java.awt.Dimension(1054, 491));
        setPreferredSize(new java.awt.Dimension(1054, 491));

        panel_Bg.setBackground(new java.awt.Color(255, 255, 255));

        panel_ToolBar.setBackground(new java.awt.Color(255, 255, 255));

        btn_QLPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_QLPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/room-key.png"))); // NOI18N
        btn_QLPhong.setText("PHÒNG");
        btn_QLPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLPhong.setInheritsPopupMenu(true);
        btn_QLPhong.setMaximumSize(new java.awt.Dimension(141, 41));
        btn_QLPhong.setMinimumSize(new java.awt.Dimension(141, 41));
        btn_QLPhong.setPreferredSize(new java.awt.Dimension(141, 41));
        btn_QLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLPhongActionPerformed(evt);
            }
        });

        btn_QLDichVu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_QLDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/tray.png"))); // NOI18N
        btn_QLDichVu.setText("DỊCH VỤ");
        btn_QLDichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLDichVu.setMaximumSize(new java.awt.Dimension(141, 41));
        btn_QLDichVu.setMinimumSize(new java.awt.Dimension(141, 41));
        btn_QLDichVu.setPreferredSize(new java.awt.Dimension(141, 41));
        btn_QLDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLDichVuActionPerformed(evt);
            }
        });

        btn_QLKhachHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_QLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/team.png"))); // NOI18N
        btn_QLKhachHang.setText("KHÁCH HÀNG");
        btn_QLKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKhachHangActionPerformed(evt);
            }
        });

        btn_QLNhanVien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_QLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/clerk.png"))); // NOI18N
        btn_QLNhanVien.setText("NHÂN VIÊN");
        btn_QLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLNhanVien.setMaximumSize(new java.awt.Dimension(141, 41));
        btn_QLNhanVien.setMinimumSize(new java.awt.Dimension(141, 41));
        btn_QLNhanVien.setPreferredSize(new java.awt.Dimension(141, 41));
        btn_QLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNhanVienActionPerformed(evt);
            }
        });

        btn_QLLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_QLLoaiPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/mortgage.png"))); // NOI18N
        btn_QLLoaiPhong.setText("LOẠI PHÒNG");
        btn_QLLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_QLLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLLoaiPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ToolBarLayout = new javax.swing.GroupLayout(panel_ToolBar);
        panel_ToolBar.setLayout(panel_ToolBarLayout);
        panel_ToolBarLayout.setHorizontalGroup(
            panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_QLPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addComponent(btn_QLDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_ToolBarLayout.setVerticalGroup(
            panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ToolBarLayout.createSequentialGroup()
                .addComponent(btn_QLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QLDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QLKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QLLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );

        panel_Content.setBackground(new java.awt.Color(255, 255, 255));
        panel_Content.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 93, 88));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_BgLayout = new javax.swing.GroupLayout(panel_Bg);
        panel_Bg.setLayout(panel_BgLayout);
        panel_BgLayout.setHorizontalGroup(
            panel_BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgLayout.createSequentialGroup()
                .addComponent(panel_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_BgLayout.setVerticalGroup(
            panel_BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_BgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_ToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //
    //điểm bắt đầu các phương thức cần thiết
    String chucvu;
    
    //show panel phù hơp với nút bấm
    public void showPanel(JPanel child){
        panel_Content.removeAll();
        panel_Content.setVisible(true);
        panel_Content.add(child);
        panel_Content.validate();
    }
    
    
    //điểm kết thúc các phương thức cần thiết
    //
    
    
    private void btn_QLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNhanVienActionPerformed
        showPanel(new jpanel_QLNhanVien());
    }//GEN-LAST:event_btn_QLNhanVienActionPerformed

    private void btn_QLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLPhongActionPerformed
        showPanel(new jpanel_QLPhong());
    }//GEN-LAST:event_btn_QLPhongActionPerformed

    private void btn_QLLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLLoaiPhongActionPerformed
        //hiển thị jpanel_QLLoaiPhong
        showPanel(new jpanel_QLLoaiPhong());
    }//GEN-LAST:event_btn_QLLoaiPhongActionPerformed

    private void btn_QLDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLDichVuActionPerformed
        showPanel(new jpanel_QLDichVu());
    }//GEN-LAST:event_btn_QLDichVuActionPerformed

    private void btn_QLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKhachHangActionPerformed
        showPanel(new jpanel_QLKhangHang());
    }//GEN-LAST:event_btn_QLKhachHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QLDichVu;
    private javax.swing.JButton btn_QLKhachHang;
    private javax.swing.JButton btn_QLLoaiPhong;
    private javax.swing.JButton btn_QLNhanVien;
    private javax.swing.JButton btn_QLPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_Bg;
    private javax.swing.JPanel panel_Content;
    private javax.swing.JPanel panel_ToolBar;
    // End of variables declaration//GEN-END:variables
}
