/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.DichVuBLL;
import Utilities.ControlFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author RumIT
 */
public class jpanel_QLDichVu extends javax.swing.JPanel {

    /**
     * Creates new form jpanel_QLDichVu
     */
    public jpanel_QLDichVu() {
        initComponents();
        
        //load dữ liệu lên bảng
        control.bindingDichVu(table_DSDichVu, dichvuBLL.getAll());
        //chuẩn hóa các trường nhập
        txt_MaDV.setText("");
        txt_TenDV.setText("");
        txt_GiaDV.setText("");
        cbb_GhiChu.removeAllItems();

        //txt_GhiChu.setText("");
        //chuẩn hóa các nút
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
        btn_XacNhan.setEnabled(false);
        table_DSDichVu.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_DSDichVu = new javax.swing.JTable();
        panel_Control = new javax.swing.JPanel();
        panel_ThongTin = new javax.swing.JPanel();
        lb_MaDV = new javax.swing.JLabel();
        lb_TenDV = new javax.swing.JLabel();
        lb_DonGia = new javax.swing.JLabel();
        lb_GhiChu = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        txt_TenDV = new javax.swing.JTextField();
        txt_GiaDV = new javax.swing.JTextField();
        cbb_GhiChu = new javax.swing.JComboBox<>();
        panel_Buttons = new javax.swing.JPanel();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_XacNhan = new javax.swing.JButton();
        panel_TimKiem = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        lb_timkiem = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(954, 438));
        setMinimumSize(new java.awt.Dimension(954, 438));
        setPreferredSize(new java.awt.Dimension(954, 438));

        table_DSDichVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_DSDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_DSDichVu.setRowHeight(20);
        table_DSDichVu.setRowMargin(2);
        table_DSDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSDichVuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_DSDichVu);

        panel_Control.setBackground(new java.awt.Color(255, 255, 255));

        panel_ThongTin.setBackground(new java.awt.Color(255, 255, 255));
        panel_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN DỊCH VỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lb_MaDV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_MaDV.setText("MÃ DỊCH VỤ");

        lb_TenDV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_TenDV.setText("TÊN DỊCH VỤ");

        lb_DonGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_DonGia.setText("ĐƠN GIÁ");

        lb_GhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_GhiChu.setText("GHI CHÚ");

        txt_TenDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenDVActionPerformed(evt);
            }
        });

        cbb_GhiChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_ThongTinLayout = new javax.swing.GroupLayout(panel_ThongTin);
        panel_ThongTin.setLayout(panel_ThongTinLayout);
        panel_ThongTinLayout.setHorizontalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_MaDV)
                    .addComponent(lb_TenDV)
                    .addComponent(lb_DonGia)
                    .addComponent(lb_GhiChu))
                .addGap(27, 27, 27)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_GiaDV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaDV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TenDV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_GhiChu, 0, 206, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ThongTinLayout.setVerticalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MaDV)
                    .addComponent(txt_MaDV, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TenDV)
                    .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_DonGia)
                    .addComponent(txt_GiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_GhiChu)
                    .addComponent(cbb_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_Buttons.setBackground(new java.awt.Color(255, 255, 255));

        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/pencil.png"))); // NOI18N
        btn_Sua.setText("SỬA");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/delete.png"))); // NOI18N
        btn_Xoa.setText("XÓA");

        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/plus.png"))); // NOI18N
        btn_Them.setText("THÊM");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_XacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_XacNhan.setText("XÁC NHẬN THÊM");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ButtonsLayout = new javax.swing.GroupLayout(panel_Buttons);
        panel_Buttons.setLayout(panel_ButtonsLayout);
        panel_ButtonsLayout.setHorizontalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ButtonsLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panel_ButtonsLayout.setVerticalGroup(
            panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ButtonsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa))
                .addGap(18, 18, 18)
                .addGroup(panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_ControlLayout = new javax.swing.GroupLayout(panel_Control);
        panel_Control.setLayout(panel_ControlLayout);
        panel_ControlLayout.setHorizontalGroup(
            panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ControlLayout.createSequentialGroup()
                .addGroup(panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ControlLayout.setVerticalGroup(
            panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ControlLayout.createSequentialGroup()
                .addComponent(panel_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TimKiem.setBackground(new java.awt.Color(255, 255, 255));

        btn_TimKiem.setText("TÌM KIẾM");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        lb_timkiem.setText("TÌM KIẾM");

        txt_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout panel_TimKiemLayout = new javax.swing.GroupLayout(panel_TimKiem);
        panel_TimKiem.setLayout(panel_TimKiemLayout);
        panel_TimKiemLayout.setHorizontalGroup(
            panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_timkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_TimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_TimKiemLayout.setVerticalGroup(
            panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_TimKiemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_timkiem)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TimKiemLayout.createSequentialGroup()
                        .addComponent(btn_TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(panel_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // -----  Khởi tạo các đối tượng cần thiết
    ControlFormat control = new ControlFormat();
    DichVuBLL dichvuBLL = new DichVuBLL();
    
    // ---------------------------------------
    private void table_DSDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSDichVuMouseClicked
        int index = table_DSDichVu.getSelectedRow();
        //đổ dữ liệu sang thông tin
        txt_MaDV.setText(table_DSDichVu.getValueAt(index, 0).toString());
        txt_TenDV.setText(table_DSDichVu.getValueAt(index, 1).toString());
        txt_GiaDV.setText(table_DSDichVu.getValueAt(index, 2).toString());
        //txt_GhiChu.setText(table_DSDichVu.getValueAt(index, 3).toString());
        cbb_GhiChu.removeAllItems();
        cbb_GhiChu.addItem("Sẵn sàng");
        cbb_GhiChu.addItem("Hết hàng");
        cbb_GhiChu.setSelectedItem(table_DSDichVu.getValueAt(index, 3).toString());
        
        //hiện nút sửa xóa
        btn_Sua.setEnabled(true);
        //btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_table_DSDichVuMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        //lấy dữ liệu từ panel_ThongTin
        String maDV = txt_MaDV.getText();
        int row = table_DSDichVu.getSelectedRow();
        boolean kiemtra = true;
        //kiểm tra nếu mã mới sửa trùng với mã cũ thì thông báo
        int rows = table_DSDichVu.getRowCount();
        for(int i = 0; i < rows; i++){
            if(i == row)
                continue;
            if(maDV.equals(table_DSDichVu.getValueAt(i, 0)))
            {
                JOptionPane.showMessageDialog(this, "Mã dịch vụ bị trùng");
                kiemtra = false;
            }
        }
        if(kiemtra == true){
            String tenDV = txt_TenDV.getText();
            String giaDV = txt_GiaDV.getText();
            String ghiChu = cbb_GhiChu.getSelectedItem().toString();
            
            String macu = table_DSDichVu.getValueAt(row, 0).toString();
            //sửa  dữ liệu 
            if(dichvuBLL.suaDichVu(maDV, tenDV, giaDV, ghiChu, macu)){
            //thông báo
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            //load lại dữ liệu lên bảng
            control.bindingDichVu(table_DSDichVu, dichvuBLL.getAll());
            //ẩn các nút
            btn_Sua.setEnabled(false);
            //btn_Xoa.setEnabled(false);
            //chuẩn hóa các trường nhập
            txt_MaDV.setText("");
            txt_TenDV.setText("");
            txt_GiaDV.setText("");
            cbb_GhiChu.removeAllItems();
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_TenDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenDVActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        //xóa các trường nhập thông tin
        txt_MaDV.setText("");
        txt_TenDV.setText("");
        txt_GiaDV.setText("");
        cbb_GhiChu.removeAllItems();
        cbb_GhiChu.addItem("Sẵn sàng");
        cbb_GhiChu.addItem("Hết hàng");
        //ẩn các nút 
        btn_Sua.setEnabled(false);
        btn_Them.setEnabled(false);
        //hiển nút xác nhận 
        btn_XacNhan.setEnabled(true);
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        //lấy dữ liệu từ các trường
        String ma = txt_MaDV.getText();
        String ten = txt_TenDV.getText();
        String gia = txt_GiaDV.getText();
        String ghichu = cbb_GhiChu.getSelectedItem().toString();
        //ghi dữ liệu
        if(dichvuBLL.themDichVu(ma, ten, gia, ghichu)){
        //thông báo
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        //chuẩn hóa lại nút và trường cho thích hợp
        txt_MaDV.setText("");
        txt_TenDV.setText("");
        txt_GiaDV.setText("");
        cbb_GhiChu.removeAllItems();
        btn_Them.setEnabled(true);
        //load lại dữ liệu
        control.bindingDichVu(table_DSDichVu, dichvuBLL.getAll());
        }
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        String key = txt_TimKiem.getText();
        control.bindingDichVu(table_DSDichVu, dichvuBLL.timkiem(key));
        txt_TimKiem.setText("");
    }//GEN-LAST:event_btn_TimKiemActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_GhiChu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_DonGia;
    private javax.swing.JLabel lb_GhiChu;
    private javax.swing.JLabel lb_MaDV;
    private javax.swing.JLabel lb_TenDV;
    private javax.swing.JLabel lb_timkiem;
    private javax.swing.JPanel panel_Buttons;
    private javax.swing.JPanel panel_Control;
    private javax.swing.JPanel panel_ThongTin;
    private javax.swing.JPanel panel_TimKiem;
    private javax.swing.JTable table_DSDichVu;
    private javax.swing.JTextField txt_GiaDV;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_TenDV;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
