/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.NhanVienBLL;
import javax.swing.JPanel;

/**
 *
 * @author RumIT
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    String chucvu;
    
    public MainForm(){
        
    }
    String MaNV;
    public MainForm(String tenNhanVien) {
        initComponents();
        this.setTitle("QUẢN LÝ KHÁCH SẠN");
        this.setLocationRelativeTo(null);
        lb_TenNV.setText(tenNhanVien);
    }
     public MainForm(String tenNhanVien, String maNV) {
        initComponents();
        this.setTitle("QUẢN LÝ KHÁCH SẠN");
        this.setLocationRelativeTo(null);
        lb_TenNV.setText(tenNhanVien);
        MaNV = maNV;
        chucvu = nhanvienBLL.layChucVu(maNV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        panel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_ToolBar = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_QuanLi = new javax.swing.JButton();
        btn_ThuePhong = new javax.swing.JButton();
        btn_HoaDon = new javax.swing.JButton();
        btn_ThongKe = new javax.swing.JButton();
        btn_TaiKhoan = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        panel_Content = new javax.swing.JPanel();
        panel_Footer = new javax.swing.JPanel();
        lb_TenNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1054, 710));
        setMinimumSize(new java.awt.Dimension(1054, 710));
        setUndecorated(true);

        panel_bg.setBackground(new java.awt.Color(255, 255, 255));

        panel_Title.setBackground(new java.awt.Color(23, 93, 88));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/logoHotel.png"))); // NOI18N

        javax.swing.GroupLayout panel_TitleLayout = new javax.swing.GroupLayout(panel_Title);
        panel_Title.setLayout(panel_TitleLayout);
        panel_TitleLayout.setHorizontalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_TitleLayout.setVerticalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_ToolBar.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_QuanLi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_QuanLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/settings.png"))); // NOI18N
        btn_QuanLi.setText("QUẢN LÝ");
        btn_QuanLi.setFocusable(false);
        btn_QuanLi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QuanLi.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_QuanLi.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_QuanLi.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_QuanLi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QuanLi);

        btn_ThuePhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ThuePhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/for-rent.png"))); // NOI18N
        btn_ThuePhong.setText("THUÊ PHÒNG");
        btn_ThuePhong.setFocusable(false);
        btn_ThuePhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ThuePhong.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_ThuePhong.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_ThuePhong.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_ThuePhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThuePhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ThuePhong);

        btn_HoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/invoice.png"))); // NOI18N
        btn_HoaDon.setText("HÓA ĐƠN");
        btn_HoaDon.setFocusable(false);
        btn_HoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_HoaDon.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_HoaDon.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_HoaDon.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_HoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoaDonActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_HoaDon);

        btn_ThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/bars-chart.png"))); // NOI18N
        btn_ThongKe.setText("THỐNG KÊ");
        btn_ThongKe.setFocusable(false);
        btn_ThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ThongKe.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_ThongKe.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_ThongKe.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_ThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ThongKe);

        btn_TaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/security.png"))); // NOI18N
        btn_TaiKhoan.setText("TÀI KHOẢN");
        btn_TaiKhoan.setFocusable(false);
        btn_TaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_TaiKhoan.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_TaiKhoan.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_TaiKhoan.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_TaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_TaiKhoan);

        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/sign-out-option.png"))); // NOI18N
        btn_Thoat.setText("THOÁT");
        btn_Thoat.setFocusable(false);
        btn_Thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Thoat.setMaximumSize(new java.awt.Dimension(110, 110));
        btn_Thoat.setMinimumSize(new java.awt.Dimension(110, 110));
        btn_Thoat.setPreferredSize(new java.awt.Dimension(110, 110));
        btn_Thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Thoat);

        javax.swing.GroupLayout panel_ToolBarLayout = new javax.swing.GroupLayout(panel_ToolBar);
        panel_ToolBar.setLayout(panel_ToolBarLayout);
        panel_ToolBarLayout.setHorizontalGroup(
            panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_ToolBarLayout.setVerticalGroup(
            panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ToolBarLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_Content.setBackground(new java.awt.Color(255, 255, 255));
        panel_Content.setMaximumSize(new java.awt.Dimension(1054, 491));
        panel_Content.setMinimumSize(new java.awt.Dimension(1054, 491));
        panel_Content.setPreferredSize(new java.awt.Dimension(1054, 491));
        panel_Content.setLayout(new java.awt.BorderLayout());

        panel_Footer.setBackground(new java.awt.Color(23, 93, 88));

        lb_TenNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TenNV.setForeground(new java.awt.Color(255, 255, 255));
        lb_TenNV.setText("Tên Nhân Viên");

        javax.swing.GroupLayout panel_FooterLayout = new javax.swing.GroupLayout(panel_Footer);
        panel_Footer.setLayout(panel_FooterLayout);
        panel_FooterLayout.setHorizontalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_FooterLayout.setVerticalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_TenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addComponent(panel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    //
    //bắt đầu các hàm cần thiết
    NhanVienBLL nhanvienBLL = new NhanVienBLL();    

    //show panel tương ứng với button trong toolbar
    public void showPanel(JPanel child){
        
        panel_Content.removeAll();
        panel_Content.setVisible(true);
        panel_Content.add(child);
        panel_Content.validate();
    }
    
    
    //kết thúc các hàm cần thiết
    //
    //
    private void btn_QuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLiActionPerformed
        showPanel(new jpanel_QuanLy(chucvu));
    }//GEN-LAST:event_btn_QuanLiActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_ThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThuePhongActionPerformed
        showPanel(new jpanel_ThuePhong(lb_TenNV.getText()));
    }//GEN-LAST:event_btn_ThuePhongActionPerformed

    private void btn_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoaDonActionPerformed
        showPanel(new jpanel_HoaDon());
    }//GEN-LAST:event_btn_HoaDonActionPerformed

    private void btn_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeActionPerformed
        showPanel(new jpanel_ThongKe());
    }//GEN-LAST:event_btn_ThongKeActionPerformed

    private void btn_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoanActionPerformed
        showPanel(new jpanel_TaiKhoan(MaNV));
    }//GEN-LAST:event_btn_TaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JButton btn_QuanLi;
    private javax.swing.JButton btn_TaiKhoan;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongKe;
    private javax.swing.JButton btn_ThuePhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lb_TenNV;
    private javax.swing.JPanel panel_Content;
    private javax.swing.JPanel panel_Footer;
    private javax.swing.JPanel panel_Title;
    private javax.swing.JPanel panel_ToolBar;
    private javax.swing.JPanel panel_bg;
    // End of variables declaration//GEN-END:variables
}
