/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CT_PhieuDichVuBLL;
import BLL.HoaDonBLL;
import BLL.KhachHangBLL;
import BLL.NhanVienBLL;
import BLL.PhieuDichVuBLL;
import BLL.PhieuThuePhongBLL;
import BLL.PhongBLL;
import Entity.PhieuThuePhong;
import Utilities.ControlFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RumIT
 */
public class TraPhongDialog extends javax.swing.JDialog {

    /**
     * Creates new form TraPhongDialog
     */
    //hàm khởi tạo mặc định
    public TraPhongDialog(java.awt.Frame parent, boolean modal){
        
    }
    
    public TraPhongDialog(java.awt.Frame parent, boolean modal,String maphieu, String maPdichvu, String tennv) {
        super(parent, modal);
        initComponents();
        maPhieuThue = maphieu;
        maPhieuDV = maPdichvu;
        tenNV = tennv;
        this.setLocationRelativeTo(null);
        this.setTitle("Trả phòng");
        
        //load dữ liệu
        //Lấy thông tin phiếu thuê
        PhieuThuePhong phieu = phieuthueBLL.layThongTin(maPhieuThue);
        //Lấy mã phòng ứng với mã phiếu thuê
        String maPhong = phieu.getMaPhong();
        //tên phòng
        lb_TenPhong.setText(phongBLL.layTenPhong(maPhong));
        //
        lb_NgayBD.setText(phieu.getNgayBD());
        //lb_NgayKT.setText(control.getToDay()); if Ngay hien tai < ngay nhap 
        lb_NgayKT.setText(phieu.getNgayKTThue());
        if(phieu.getKHNgoaiQuoc().equals("1"))
            lb_KhachNuocNgoai.setText("Có");
        else
            lb_KhachNuocNgoai.setText("Không");
        String maKH = phieu.getMaKH();
        //từ mã khách hàng lấy tên
        lb_TenKH.setText(khachBLL.layTen(maKH));
        //từ mã khách hàng lấy cmnd
        lb_CMND.setText(khachBLL.layCMND(maKH));
        
        //lấy danh sách order và load lên bảng
        control.bindingOrder(table_Order, ctPhieuDVBLL.layDichVuTheoPhieu(maPhieuDV));
        int count = table_Order.getRowCount();
        Double sum = 0.0;
        for(int i = 0; i < count; i++){
            sum = sum + Double.parseDouble(table_Order.getValueAt(i, 3).toString());
        }
        lb_TienDichVu.setText(""+sum);
        
        //Tiền phiếu thuê
        String[] gia = phongBLL.layGiaTheoMaPhong(maPhong);
        double tienquadem = Double.parseDouble(gia[0]);
        double tiengiodau = Double.parseDouble(gia[1]);
        String ngayBD = lb_NgayBD.getText();
        String ngayKT = lb_NgayKT.getText();
        String tien="";
        try {
            tien = control.tienthue(ngayBD, ngayKT, tiengiodau, tienquadem);
        } catch (ParseException ex) {
            Logger.getLogger(TraPhongDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        lb_TienThue.setText(""+tien);
        
        //Tổng tiền
        double tongtien = Double.parseDouble(tien) + sum;
        lb_TongTien.setText(""+tongtien);
    }

    //
    private String maPhieuThue;
    private String maPhieuDV;
    PhieuThuePhongBLL phieuthueBLL = new PhieuThuePhongBLL();
    CT_PhieuDichVuBLL ctPhieuDVBLL = new CT_PhieuDichVuBLL();
    PhieuDichVuBLL phieuDVBLL = new PhieuDichVuBLL();
    ControlFormat control = new ControlFormat();
    KhachHangBLL khachBLL = new KhachHangBLL();
    PhongBLL phongBLL = new PhongBLL();
    private String tenNV;
    NhanVienBLL nhanvienBLL = new NhanVienBLL();
    HoaDonBLL  hoadonBLL = new HoaDonBLL();
    //
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        panel_Title = new javax.swing.JPanel();
        lb_Title = new javax.swing.JLabel();
        panel_Content = new javax.swing.JPanel();
        lb_TenPhong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Order = new javax.swing.JTable();
        panel_ThongTinThue = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_TenKH = new javax.swing.JLabel();
        lb_KhachNuocNgoai = new javax.swing.JLabel();
        lb_NgayBD = new javax.swing.JLabel();
        lb_NgayKT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_CMND = new javax.swing.JLabel();
        lb_TienThue = new javax.swing.JLabel();
        lb_TienDichVu = new javax.swing.JLabel();
        panel_Footer = new javax.swing.JPanel();
        btn_Huy = new javax.swing.JButton();
        btn_XacNhan = new javax.swing.JButton();
        lb_TongTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bg.setBackground(new java.awt.Color(255, 255, 255));

        panel_Title.setBackground(new java.awt.Color(23, 93, 88));

        lb_Title.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(255, 255, 255));
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("TRẢ PHÒNG");

        javax.swing.GroupLayout panel_TitleLayout = new javax.swing.GroupLayout(panel_Title);
        panel_Title.setLayout(panel_TitleLayout);
        panel_TitleLayout.setHorizontalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_TitleLayout.setVerticalGroup(
            panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panel_Content.setBackground(new java.awt.Color(255, 255, 255));

        lb_TenPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TenPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TenPhong.setText("Phòng");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ đã dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        table_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_Order);

        panel_ThongTinThue.setBackground(new java.awt.Color(255, 255, 255));
        panel_ThongTinThue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thuê phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Tên khách hàng");

        jLabel2.setText("Ngày bắt đầu");

        jLabel3.setText("Khách nước ngoài?");

        jLabel4.setText("Ngày trả phòng");

        lb_TenKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_TenKH.setText("Tên");

        lb_KhachNuocNgoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_KhachNuocNgoai.setText("có/không");

        lb_NgayBD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_NgayBD.setText("Bắt đầu");

        lb_NgayKT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_NgayKT.setText("Trả phòng");

        jLabel5.setText("CMND");

        lb_CMND.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_CMND.setText("CMND");

        javax.swing.GroupLayout panel_ThongTinThueLayout = new javax.swing.GroupLayout(panel_ThongTinThue);
        panel_ThongTinThue.setLayout(panel_ThongTinThueLayout);
        panel_ThongTinThueLayout.setHorizontalGroup(
            panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinThueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ThongTinThueLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lb_KhachNuocNgoai, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .addGroup(panel_ThongTinThueLayout.createSequentialGroup()
                        .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_NgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_NgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_CMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_TenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_ThongTinThueLayout.setVerticalGroup(
            panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinThueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_TenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_CMND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_KhachNuocNgoai))
                .addGap(18, 18, 18)
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NgayBD)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panel_ThongTinThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_NgayKT))
                .addContainerGap())
        );

        lb_TienThue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_TienThue.setForeground(new java.awt.Color(0, 0, 204));
        lb_TienThue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_TienThue.setText("0");

        lb_TienDichVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_TienDichVu.setForeground(new java.awt.Color(0, 0, 204));
        lb_TienDichVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_TienDichVu.setText("0");

        javax.swing.GroupLayout panel_ContentLayout = new javax.swing.GroupLayout(panel_Content);
        panel_Content.setLayout(panel_ContentLayout);
        panel_ContentLayout.setHorizontalGroup(
            panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_TenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ContentLayout.createSequentialGroup()
                .addGroup(panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_TienThue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ThongTinThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(lb_TienDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_ContentLayout.setVerticalGroup(
            panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContentLayout.createSequentialGroup()
                .addComponent(lb_TenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_ThongTinThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TienThue, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lb_TienDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_Footer.setBackground(new java.awt.Color(255, 255, 255));

        btn_Huy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Huy.setForeground(new java.awt.Color(23, 93, 88));
        btn_Huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/logout-24.png"))); // NOI18N
        btn_Huy.setText("Hủy thao tác");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        btn_XacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_XacNhan.setForeground(new java.awt.Color(23, 93, 88));
        btn_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libs/image/xacnhan-24.png"))); // NOI18N
        btn_XacNhan.setText("Xác nhận trả");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_FooterLayout = new javax.swing.GroupLayout(panel_Footer);
        panel_Footer.setLayout(panel_FooterLayout);
        panel_FooterLayout.setHorizontalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_FooterLayout.setVerticalGroup(
            panel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_XacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
            .addComponent(btn_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lb_TongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_TongTien.setForeground(new java.awt.Color(204, 0, 0));
        lb_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_TongTien.setText("0");

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addComponent(panel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        //Xử lí đối với phiếu thuê phòng
        //Cập nhập ngày kết thúc và tình trạng phiếu
        boolean kiemtra = true;
        if(!phieuthueBLL.xulyTraPhong(maPhieuThue, lb_NgayKT.getText())){
            JOptionPane.showMessageDialog(this, "Chưa cập nhập được phiếu thuê");
            kiemtra = false;
        }
        //Xử lí với phiếu dịch vụ
        //Cập nhập tiền dịch vụ và ngày lập
        //if(!phieuDVBLL.xulyTraPhong(maPhieuDV, lb_TienThue.getText(), lb_NgayKT.getText())){
        //    JOptionPane.showMessageDialog(this, "Chưa cập nhập đc phiếu dịch vụ");
        //    kiemtra = false;
        //}
        //xử lí với hóa đơn
        //cập nhập tiền DV, tiền phòng, ngayHD, trigia, MANV;
        String MaNV = nhanvienBLL.getIDbyName(tenNV);
        String mahd = hoadonBLL.getMaHD(maPhieuThue);
        if(!hoadonBLL.xulyTraPhong(mahd, lb_TienDichVu.getText(), lb_TienThue.getText(), lb_TongTien.getText(), lb_NgayKT.getText(), MaNV)){
            JOptionPane.showMessageDialog(this, "Chưa cập nhập đc hóa đơn");
            kiemtra = false;
        }
        //Đặt lại trạng thái phòng
        if(!phongBLL.xulyTraPhong(phongBLL.getIDbyName(lb_TenPhong.getText()))){
            JOptionPane.showMessageDialog(this, "Chưa cập nhập tình trạng phòng");
            kiemtra = false;
        }
        if(kiemtra == true){
            JOptionPane.showMessageDialog(this, "Trả phòng thành công");
            //JFrame main;
            //main = (JFrame) SwingUtilities.getWindowAncestor(new MainForm());
            //main.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi");
        }
    
    }//GEN-LAST:event_btn_XacNhanActionPerformed
    
    public boolean reload(){
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraPhongDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraPhongDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraPhongDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraPhongDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraPhongDialog dialog = new TraPhongDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_CMND;
    private javax.swing.JLabel lb_KhachNuocNgoai;
    private javax.swing.JLabel lb_NgayBD;
    private javax.swing.JLabel lb_NgayKT;
    private javax.swing.JLabel lb_TenKH;
    private javax.swing.JLabel lb_TenPhong;
    private javax.swing.JLabel lb_TienDichVu;
    private javax.swing.JLabel lb_TienThue;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_TongTien;
    private javax.swing.JPanel panel_Content;
    private javax.swing.JPanel panel_Footer;
    private javax.swing.JPanel panel_ThongTinThue;
    private javax.swing.JPanel panel_Title;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JTable table_Order;
    // End of variables declaration//GEN-END:variables
}
